### ISSUE TITLE
How to update the size manually using tunasynctl

### ISSUE THREAD

**Issue by leochen12-rgb** [tuna/tunasync#179]
tunasynctl -w “worker-id" "mirro" "size”

How to  get worker id
Which field is the mirror
What unit is size

**Comment by shankerwangmiao** [comment]
Woker Id is declared in the `name = ` field in the `[global]` section of the configuration of the worker. When a worker is successfully registered with the manager, it can be shown in `tunasynctl workers`. Since normally the size can be reported by a worker automatically, when size is set manually, worker id should be included to act on behalf of that worker.

the field `<mirror>` indicates the mirror the size of which will be set.

the field `<size>` indicates the size of that mirror. Currently, `<size>` is stored purely as a string, so you can use any unit you want.

The correct usage should be:

```
tunasynctl set-size -w <worker-id> <mirror> <size>
```

**Comment by shankerwangmiao** [comment]
I have fixed the misleading message in commit [60f92ce](https://github.com/tuna/tunasync/commit/60f92ceebbfc4ba750b956c8e849cdd55d82f8a6)

**Comment by shankerwangmiao** [comment]
> I want to know how Tuna counts the size of a mirror directory for some very large TB directories when it has a large number of directory levels and files. I currently use du or duc to calculate the directory size, which takes a long time.

Normally we do not use `du` to calculate the size, since the expense on disk IO is too high. The size of mirrors using `rsync` is extracted automatically from the output of `rsync`. In terms of other mirrors using custom scripts, some of the scripts we provided in https://github.com/tuna/tunasync-scripts can give a total size of the mirror in the end of output, which can then be matched by the regex defined in the configuration of the worker. For example, the script for the mirror `github-releases` is handled by the script https://github.com/tuna/tunasync-scripts/blob/master/github-release.py, the total size is given out at https://github.com/tuna/tunasync-scripts/blob/cae1194534d6cce0ddea031a2bf318b9aa0261a3/github-release.py#L296 , and the capture regex is defined at https://github.com/tuna/tunasync/blob/60f92ceebbfc4ba750b956c8e849cdd55d82f8a6/docs/zh_CN/workers.conf#L247 .
